<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>pax</string>
    </array>
    <key>name</key>
    <string>PAX</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#control_flow</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#tags</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#settings</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#handlers</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comments</key>
      <dict>
        <key>applyEndPatternLast</key>
        <true/>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.line.pax</string>
            <key>match</key>
            <string>//.*</string>
          </dict>
          <dict>
            <key>name</key>
            <string>comment.block.pax</string>
            <key>begin</key>
            <string>/\*</string>
            <key>end</key>
            <string>\*/</string>
          </dict>
        </array>
      </dict>
      <key>identifier</key>
      <dict>
        <key>name</key>
        <string>variable.pax</string>
        <key>match</key>
        <string>\b([a-zA-Z_][a-zA-Z0-9_]*)</string>
      </dict>
      <key>tags</key>
      <dict>
        <key>name</key>
        <string>meta.tag.pax</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#open_self_tag</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#close_tag</string>
          </dict>
        </array>
      </dict>
      <key>open_self_tag</key>
      <dict>
        <key>name</key>
        <string>meta.tag.pax</string>
        <key>begin</key>
        <string>(&lt;([A-Z][a-zA-Z0-9_]*))</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.class.pax</string>
          </dict>
        </dict>
        <key>end</key>
        <string>/&gt;|&gt;</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>support.class.pax</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#attributeKeys</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#attributeValues</string>
          </dict>
        </array>
      </dict>
      <key>close_tag</key>
      <dict>
        <key>name</key>
        <string>support.class.pax</string>
        <key>match</key>
        <string>&lt;/[A-Z][a-zA-Z0-9_]*&gt;</string>
      </dict>
      <key>attributeKeys</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#identifier</string>
            <key>match</key>
            <string>\s*=</string>
          </dict>
        </array>
      </dict>
      <key>attributeValues</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#literal_object</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literal_value</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#identifier</string>
          </dict>
        </array>
      </dict>
      <key>expression</key>
      <dict>
        <key>name</key>
        <string>variable.parameter</string>
        <key>begin</key>
        <string>{</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.braces.begin.pax</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.braces.end.pax</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expression_body</string>
          </dict>
        </array>
      </dict>
      <key>expression_body</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#literal_object</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#xo-range</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#xo-prefix</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#xo-infix</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#xo-list</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literal_value</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#xo-symbol</string>
          </dict>
        </array>
      </dict>
      <key>xo-function-call</key>
      <dict>
        <key>name</key>
        <string>comment.function.call</string>
        <key>match</key>
        <string>[A-Za-z_][A-Za-z0-9_]*(::[A-Za-z_][A-Za-z0-9_]*)?\(</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expression_body</string>
          </dict>
        </array>
      </dict>
      <key>xo-range</key>
      <dict>
        <key>match</key>
        <string>(\d+)\.{2}(\d+)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#literal_value</string>
              </dict>
            </array>
          </dict>
          <key>2</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#literal_value</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>name</key>
        <string>keyword.list.pax</string>
      </dict>
      <key>xo-prefix</key>
      <dict>
        <key>match</key>
        <string>\b(?:-|!)\b</string>
        <key>name</key>
        <string>keyword.operator.prefix.pax</string>
      </dict>
      <key>xo-infix</key>
      <dict>
        <key>match</key>
        <string>\+|&amp;&amp;|\|\||\/|\^|%%|\*|==|&gt;|&gt;=|&lt;|&lt;=|!=|-|\?|:</string>
        <key>name</key>
        <string>keyword.infix.pax</string>
      </dict>
      <key>xo-symbol</key>
      <dict>
        <key>name</key>
        <string>variable.symbol.pax</string>
        <key>match</key>
        <string>\b\$?[A-Za-z_][A-Za-z0-9_]*(\.[A-Za-z_][A-Za-z0-9_]*)?\b</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>variable.symbol.pax</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#expression_body</string>
              </dict>
            </array>
          </dict>
        </dict>
      </dict>
      <key>xo-list</key>
      <dict>
        <key>begin</key>
        <string>\[</string>
        <key>end</key>
        <string>\]</string>
        <key>contentName</key>
        <string>markup.list.pax</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expression_body</string>
          </dict>
        </array>
      </dict>
      <key>literal_value</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#literal_number_with_unit</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literal_number</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literal_tuple</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literal_enum_value</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literal_boolean</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string</string>
          </dict>
        </array>
      </dict>
      <key>literal_number_with_unit</key>
      <dict>
        <key>name</key>
        <string>constant.numeric.pax</string>
        <key>match</key>
        <string>\b\d+(%|px|deg|rad)</string>
      </dict>
      <key>literal_number</key>
      <dict>
        <key>name</key>
        <string>constant.numeric.pax</string>
        <key>match</key>
        <string>\b\d+(\.\d+)?\b</string>
      </dict>
      <key>literal_tuple</key>
      <dict>
        <key>begin</key>
        <string>\(</string>
        <key>end</key>
        <string>\)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#xo-infix</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literal_value</string>
          </dict>
          <dict>
            <key>name</key>
            <string>punctuation.separator.comma.pax</string>
            <key>match</key>
            <string>,</string>
          </dict>
        </array>
      </dict>
      <key>literal_enum_value</key>
      <dict>
        <key>name</key>
        <string>entity.name.function</string>
        <key>match</key>
        <string>\b[A-Z][a-zA-Z0-9_]*::[a-zA-Z0-9_]*(\([a-zA-Z0-9_,]*\))?</string>
      </dict>
      <key>literal_boolean</key>
      <dict>
        <key>name</key>
        <string>constant.language.boolean.pax</string>
        <key>match</key>
        <string>\b(true|false)\b</string>
      </dict>
      <key>string</key>
      <dict>
        <key>name</key>
        <string>string.quoted.double.pax</string>
        <key>begin</key>
        <string>"</string>
        <key>end</key>
        <string>"</string>
      </dict>
      <key>settings</key>
      <dict>
        <key>name</key>
        <string>keyword.settings.pax</string>
        <key>begin</key>
        <string>@settings\s*\{</string>
        <key>end</key>
        <string>\}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#selector_block</string>
          </dict>
        </array>
      </dict>
      <key>selector_block</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#selector</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literal_object</string>
          </dict>
        </array>
      </dict>
      <key>selector</key>
      <dict>
        <key>name</key>
        <string>variable.selector.pax</string>
        <key>match</key>
        <string>([.#])([a-zA-Z0-9_]+)</string>
      </dict>
      <key>literal_object</key>
      <dict>
        <key>name</key>
        <string>variable.literal_object.pax</string>
        <key>begin</key>
        <string>\{</string>
        <key>end</key>
        <string>\}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#settings_key_value_pair</string>
          </dict>
        </array>
      </dict>
      <key>settings_key_value_pair</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#settings_key</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#settings_value</string>
          </dict>
        </array>
      </dict>
      <key>settings_key</key>
      <dict>
        <key>include</key>
        <string>#identifier</string>
        <key>match</key>
        <string>\s*:\b</string>
      </dict>
      <key>settings_value</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#literal_value</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#literal_object</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
      <key>handlers</key>
      <dict>
        <key>name</key>
        <string>keyword.handlers.pax</string>
        <key>begin</key>
        <string>@handlers\s*\{</string>
        <key>end</key>
        <string>\}</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#handlers_key_value_pair</string>
          </dict>
        </array>
      </dict>
      <key>handlers_key_value_pair</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#handlers_key</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#handlers_value</string>
          </dict>
        </array>
      </dict>
      <key>handlers_key</key>
      <dict>
        <key>include</key>
        <string>#identifier</string>
        <key>match</key>
        <string>\s*:</string>
      </dict>
      <key>handlers_value</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#literal_function</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function_list</string>
          </dict>
        </array>
      </dict>
      <key>literal_function</key>
      <dict>
        <key>name</key>
        <string>entity.name.function.pax</string>
        <key>match</key>
        <string>\b(self\.)?([a-zA-Z_][a-zA-Z0-9_]*),?</string>
      </dict>
      <key>function_list</key>
      <dict>
        <key>name</key>
        <string>meta.function-list.pax</string>
        <key>begin</key>
        <string>\[</string>
        <key>end</key>
        <string>\]</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#literal_function</string>
          </dict>
        </array>
      </dict>
      <key>control_flow</key>
      <dict>
        <key>name</key>
        <string>entity.name.section.control.pax</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#statement_for</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#statement_if</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#statement_slot</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#closing_brace</string>
          </dict>
        </array>
      </dict>
      <key>closing_brace</key>
      <dict>
        <key>name</key>
        <string>keyword.control.brace.end.pax</string>
        <key>match</key>
        <string>}</string>
      </dict>
      <key>statement_if</key>
      <dict>
        <key>name</key>
        <string>keyword.control.if.pax</string>
        <key>begin</key>
        <string>if</string>
        <key>end</key>
        <string>{</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#expression</string>
          </dict>
        </array>
      </dict>
      <key>statement_for</key>
      <dict>
        <key>name</key>
        <string>meta.control.for.pax</string>
        <key>begin</key>
        <string>for</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword.control.for.pax</string>
          </dict>
        </dict>
        <key>end</key>
        <string>{</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword.control.for.pax</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.control.in.pax</string>
            <key>match</key>
            <string>in</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#xo-range</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#identifier</string>
          </dict>
        </array>
      </dict>
      <key>statement_slot</key>
      <dict>
        <key>name</key>
        <string>keyword.control.slot.pax</string>
        <key>match</key>
        <string>slot</string>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.pax</string>
  </dict>
</plist>